name: Docker Image Ellis-CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${GITHUB_ACTOR}/alura-devops-gcp:$(date +%s)

    - uses: actions/checkout@v4
    - name: Push the Docker image
      run: docker push ${GITHUB_ACTOR}/alura-devops-gcp:$(date +%s)
          
